function [fy,fx,fyp,fxp,fv,out6] = pset7_model_df(in1)
%PSET7_MODEL_DF
%    [FY,FX,FYP,FXP,FV,OUT6] = PSET7_MODEL_DF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    08-Dec-2024 13:28:51

alpha = in1(:,3);
bet = in1(:,1);
chi = in1(:,7);
deltak = in1(:,4);
deltan = in1(:,5);
eps = in1(:,8);
phin = in1(:,6);
rho = in1(:,9);
sig = in1(:,2);
et1 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
et2 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
et3 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
et4 = phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
et5 = -((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
et6 = (chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
et7 = phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
et8 = -((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
et9 = (chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
mt1 = [0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,(bet.*sig.*(-deltak+alpha.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0)+1.0))./(et7+et8+et9),-(bet.*phin.*sig.*(deltan-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps+1.0))./(chi.*eps.*(et4+et5+et6)),0.0,-1.0,0.0,0.0,0.0,0.0,-(et1+et2+et3).^(-sig),0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0];
mt2 = [-(alpha.*deltan.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0).*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(alpha-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./chi];
mt3 = [(alpha-1.0).*((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha,0.0,0.0,1.0,0.0,-1.0,0.0,0.0];
mt4 = [-(phin.*(eps-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./(chi.*eps),0.0,-phin,0.0,-chi.*eps.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(eps-1.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0];
fy = reshape([mt1,mt2,mt3,mt4],9,6);
if nargout > 1
    mt5 = [0.0,(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0),-((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha,0.0,0.0,0.0];
    mt6 = [-rho,0.0,0.0,0.0,(alpha.*deltan.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0).*(alpha-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./chi];
    mt7 = [-alpha.*((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(alpha-1.0),0.0,deltak-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,deltan-1.0,0.0,0.0,0.0];
    fx = reshape([mt5,mt6,mt7],9,3);
end
if nargout > 2
    et10 = phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et11 = -((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et12 = (chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et13 = phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et14 = -((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et15 = (chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    mt8 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-(bet.*sig.*(-deltak+alpha.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0)+1.0))./(et13+et14+et15),(bet.*phin.*sig.*(deltan-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps+1.0))./(chi.*eps.*(et10+et11+et12)),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
    mt9 = [(alpha.*bet.*deltan.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-2.0).*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(alpha-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./chi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
    mt10 = [-(bet.*phin.*(deltan-1.0).*(eps-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./(chi.*eps),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-bet];
    fyp = reshape([mt8,mt9,mt10],9,6);
end
if nargout > 3
    fxp = reshape([-alpha.*bet.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0),0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-(alpha.*bet.*deltan.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-2.0).*(alpha-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps))./chi,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[9,3]);
end
if nargout > 4
    et16 = (chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan-(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et17 = (chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(deltak-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et18 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et19 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et20 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et21 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et22 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et23 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et24 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et25 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et26 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    mt11 = [-bet.*(-deltak+alpha.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^(alpha-1.0)+1.0)+1.0];
    mt12 = [(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0)+(phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps+1.0))./(chi.*eps)+(bet.*phin.*(deltan-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^(-eps+1.0))./(chi.*eps),0.0,0.0,et16+et17];
    mt13 = [-chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps+(chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan+(chi.*(deltan-1.0).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan];
    mt14 = [0.0,0.0,(et18+et19+et20).^(-sig+1.0)./(sig-1.0)+(et21+et22+et23).^(-sig+1.0)./((bet-1.0).*(sig-1.0))-(bet.*(et24+et25+et26).^(-sig+1.0))./((bet-1.0).*(sig-1.0))];
    fv = [mt11,mt12,mt13,mt14];
end
if nargout > 5
    et27 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et28 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et29 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    et30 = -phin.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0));
    et31 = ((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha;
    et32 = -(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan;
    mt15 = [((chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^(-alpha+1.0).*((chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan).^alpha,et27+et28+et29];
    mt16 = [(chi.*deltak.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan,(chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan];
    mt17 = [(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)),(et30+et31+et32).^(-sig+1.0)./((bet-1.0).*(sig-1.0)),1.0,(chi.*((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0)).*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan];
    mt18 = [(chi.*(-(chi.*eps.*(((deltak+1.0./bet-1.0)./alpha).^(1.0./(alpha-1.0))).^alpha.*(alpha-1.0))./(phin.*(bet.*(deltan-1.0)+1.0))).^(-1.0./(eps-1.0)).^eps)./deltan];
    out6 = [mt15,mt16,mt17,mt18];
end
end
